//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NntpClientLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NntpClientLib.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to setup session after connection to NNTP server..
        /// </summary>
        internal static string ErrorMessage01 {
            get {
                return ResourceManager.GetString("ErrorMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP command failed..
        /// </summary>
        internal static string ErrorMessage02 {
            get {
                return ResourceManager.GetString("ErrorMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect direction command, it must be LAST or NEXT..
        /// </summary>
        internal static string ErrorMessage03 {
            get {
                return ResourceManager.GetString("ErrorMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move the selected article cursor in the current group..
        /// </summary>
        internal static string ErrorMessage04 {
            get {
                return ResourceManager.GetString("ErrorMessage04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get statistics for current group..
        /// </summary>
        internal static string ErrorMessage05 {
            get {
                return ResourceManager.GetString("ErrorMessage05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not post to group..
        /// </summary>
        internal static string ErrorMessage06 {
            get {
                return ResourceManager.GetString("ErrorMessage06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article failed to post to group..
        /// </summary>
        internal static string ErrorMessage07 {
            get {
                return ResourceManager.GetString("ErrorMessage07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave command failed..
        /// </summary>
        internal static string ErrorMessage08 {
            get {
                return ResourceManager.GetString("ErrorMessage08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Id must begin with &lt; and end with &gt;..
        /// </summary>
        internal static string ErrorMessage09 {
            get {
                return ResourceManager.GetString("ErrorMessage09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Id must begin with &lt; and end with &gt; and contain a message..
        /// </summary>
        internal static string ErrorMessage10 {
            get {
                return ResourceManager.GetString("ErrorMessage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client is not connected to server..
        /// </summary>
        internal static string ErrorMessage11 {
            get {
                return ResourceManager.GetString("ErrorMessage11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NNTP command failed, unexpected response code..
        /// </summary>
        internal static string ErrorMessage12 {
            get {
                return ResourceManager.GetString("ErrorMessage12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response input string should contain at least 3 fields, possibly 4..
        /// </summary>
        internal static string ErrorMessage13 {
            get {
                return ResourceManager.GetString("ErrorMessage13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required password was not accepted..
        /// </summary>
        internal static string ErrorMessage30 {
            get {
                return ResourceManager.GetString("ErrorMessage30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate..
        /// </summary>
        internal static string ErrorMessage31 {
            get {
                return ResourceManager.GetString("ErrorMessage31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No previous response was received..
        /// </summary>
        internal static string ErrorMessage41 {
            get {
                return ResourceManager.GetString("ErrorMessage41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response code is missing..
        /// </summary>
        internal static string ErrorMessage42 {
            get {
                return ResourceManager.GetString("ErrorMessage42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum size of the buffer must be positive..
        /// </summary>
        internal static string ErrorMessage43 {
            get {
                return ResourceManager.GetString("ErrorMessage43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read stream..
        /// </summary>
        internal static string ErrorMessage44 {
            get {
                return ResourceManager.GetString("ErrorMessage44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not read from underlying stream..
        /// </summary>
        internal static string ErrorMessage45 {
            get {
                return ResourceManager.GetString("ErrorMessage45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized date format requested, &apos;R&apos; is the only accepted format argument..
        /// </summary>
        internal static string ErrorMessage46 {
            get {
                return ResourceManager.GetString("ErrorMessage46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is not a valid date time..
        /// </summary>
        internal static string ErrorMessage47 {
            get {
                return ResourceManager.GetString("ErrorMessage47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response input string should contain 2 or 3 fields separated by spaces..
        /// </summary>
        internal static string ErrorMessage48 {
            get {
                return ResourceManager.GetString("ErrorMessage48", resourceCulture);
            }
        }
    }
}
