INSERT INTO [dbo].[Kooboo_CMS_Account_Users]
           ([Email]
           ,[UserName]
           ,[Password]
           ,[IsAdministrator]
           ,[UICulture]
           ,[PasswordSalt]
           ,[IsApproved]
           ,[IsLockedOut]
           ,[FailedPasswordAttemptCount]
           ,[UtcLastLockoutDate]
           ,[UtcLastLoginDate]
           ,[UtcLastPasswordChangedDate]
           ,[ActivateCode]
           ,[CustomFieldsXml])
     VALUES
           ('admin@kooboo.com'
           ,'admin'
           ,'FYOL44w+oWRo53/9NQCnqa8RS00='
           ,1
           ,''
           ,'aKEwnA2Riwo4SCzyYFfzFw=='
           ,1
           ,0
           ,0
           ,getdate()
           ,getdate()
           ,getdate()
           ,''
           ,'')